name: meu_app
description: 'Exercícios práticos do curso "Dart: trabalhando com a sintaxe e configuração de projeto" da Alura'
version: 1.5.0
repository: https://github.com/OYanEnrique/dart-exercises

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
